### DISCUSSION TITLE
Community testing the pydantic model branch

### DISCUSSION THREAD

**Discussion by jsamoocha** [hozn/stravalib#344] [Team Posts]
I'm not an expert on releasing packages, so I wonder if it's possible to create a pre-release, e.g. `1.3.0.rc1`, which is based on our `pydantic_model` branch (which will be rebased on master) for making it easier for the community to test?

Is this possible with our current build/release setup? Or will it require substantial configuration changes? (In case of which we can ask the community to install the branch directly from Github as we did ourselves)

**Comment by lwasser** [comment]
Hi! I can look into this ..this weekend. My understanding is that pip knows
not to install a release candidate version by default. As such a tagged
version w .rcx could work w our current system.

 However let me dig a bit more to ensure my understanding is correct! I've
also never released from a branch but it should all be doable. We can
always do a manual release w a tagged archive for this too. That is simple.

**Comment by lwasser** [comment]
Ok i did look into this just a bit more. 
Right now our workflow is such that i build the package only when pushed to master branch. so the build is based on files in master

i'm using this action to push to pypi and notice this:
https://github.com/pypa/gh-action-pypi-publish#non-goals (we build the distribution, action then publishes)

Now i could potentially get creative with the action to allow to build from other branches IF we create a release on another branch. what do you think about this workflow:

1. Update our release workflow to be [something like this??](https://stackoverflow.com/questions/71083657/trigger-github-workflow-only-on-the-release-tag-event-and-specific-path) OR update the workflow to build from whatever branch the release is on (i don't know how to do this but i suspect we can figure it out?)

something like

1. identify what branch the release uses - something like: `github.event.release.target_commitish` 
2. grab files from that branch and build SDist and wheel
3. then push that to pypi using the rc0 element

## Then our workflow would be:
1. Create a release using the Pydantic branch - this is easy
2. let actions do the work to release 

@jsamoocha did you say that you were running actions locally somehow to test? this will be a bit tricky but if i can create a wheel, then i can look at the file content to make sure it's being created from the correct branch locally (maybe?).

**Reply by jsamoocha** [reply]
I use(d) [act](https://github.com/nektos/act) for testing workflows locally, but it stopped working because of some changes that we introduced (which is a bug on their end).

> something like
>1. identify what branch the release uses - something like: github.event.release.target_commitish
>2. grab files from that branch and build SDist and wheel
>3. then push that to pypi using the rc0 element

I think the following (from the actions/checkout README) may be helpful:

```yaml
- uses: actions/checkout@v3
  with:
    # Repository name with owner. For example, actions/checkout
    # Default: ${{ github.repository }}
    repository: ''

    # The branch, tag or SHA to checkout. When checking out the repository that
    # triggered a workflow, this defaults to the reference or SHA for that event.
    # Otherwise, uses the default branch.
    ref: ''  <-- This can be the exact tag that we create for the release, right?
```

So it seems like we could use some other ref than the default `master`?
